### ISSUE TITLE
v2 release checklist

### ISSUE THREAD

**Issue by desandro** [metafizzy/isotope#613]
- [x] [CodePen demos](http://codepen.io/desandro/tag/isotope-docs) for every demo in the docs
- [x] Check redirects that isotope.metafizzy.co/beta URLs don't break
- [x] Integrate Outlayer v1.2
- [x] Update Masonry for Outlayer v1.2
- [x] Create site for v1 isotope.metafizzy.co/v1
- [x] Add dist/ with isotope.pkgd.js and isotope.pkgd.min.js #635 
- [x] Remove requirejs stuff from isotope-docs

Shelving
- ~~Integrate Outlayer with [Transitn](https://github.com/desandro/transitn)~~ (opted not to do this)
- ~~change repo to metafizzy/isotope~~ #591
- ~~Update bower registry~~
